---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint
    commands:
      - yamllint -d relaxed .drone.yml

  - name: gofmt
    depends_on:
      - yamllint
    image: golang:1.14
    commands:
      - go fmt

  - name: gotest
    depends_on:
      - gofmt
    image: golang:1.14
    commands:
      - go test

  - name: build
    depends_on:
      - gotest
    image: golang:1.14
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -o chitchat

  - name: run
    depends_on:
      - build
    image: curlimages/curl:7.70.0
    commands:
      - cp ./chitchat /var/run/chitchat
      - cd /var/run
      - ./chitchat &
      - curl -v http://127.0.0.1:8080

  - name: dockerhub
    depends_on:
      - yamllint
    image: plugins/docker
    settings:
      repo: hsmtkk/chitchat
      username: hsmtkk
      password:
        from_secret: docker_hub_token
      auto_tag: true

